name: Tauri Mobile Builds

# 配置为手动触发
on:
  workflow_dispatch:
    inputs:
      tauriVersion:
        description: 'Tauri 版本 (可选)'
        required: false
        default: ''

jobs:
  build-mobile:
    # iOS 构建需要 macOS 环境
    runs-on: macos-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 设置 Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android, armv7-linux-androideabi, x86_64-linux-android, i686-linux-android

      - name: 安装依赖
        run: |
          npm install
          # 安装 Tauri CLI (如果项目中未包含)
          cargo install tauri-cli --version ${{ github.event.inputs.tauriVersion || 'latest' }}

      - name: 安装 Android 构建工具
        uses: android-actions/setup-android@v3

      - name: 构建安卓版本
        run: |
          # 设置安卓环境变量
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          # 构建未签名的安卓 APK
          cargo tauri build --target aarch64-linux-android --android --no-sign

      - name: 构建 iOS 版本
        run: |
          # 构建未签名的 iOS 应用
          cargo tauri build --ios --no-sign

      - name: 上传安卓构建产物
        uses: actions/upload-artifact@v4
        with:
          name: tauri-android-build
          path: |
            src-tauri/target/aarch64-linux-android/release/bundle/android/*.apk
            src-tauri/target/aarch64-linux-android/release/bundle/android/*.aab

      - name: 上传 iOS 构建产物
        uses: actions/upload-artifact@v4
        with:
          name: tauri-ios-build
          path: src-tauri/target/x86_64-apple-ios/release/bundle/ios/*.app
