name: Build Tauri Mobile Apps

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Set up Rust
      uses: actions-rs/toolchain@0.1.8
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Install Android SDK
      uses: android-actions/setup-sdk@v3
      with:
        android-version: '34'
        java-version: '11'
        ndk: true
    - name: Set environment variables for Android build
      run: |
        echo "ANDROID_KEYSTORE_PATH=${{ secrets.ANDROID_KEYSTORE_PATH }}" >> $GITHUB_ENV
        echo "ANDROID_KEYSTORE_PASSWORD=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
        echo "ANDROID_KEY_ALIAS=${{ secrets.ANDROID_KEY_ALIAS }}" >> $GITHUB_ENV
        echo "ANDROID_KEY_PASSWORD=${{ secrets.ANDROID_KEY_PASSWORD }}" >> $GITHUB_ENV
    - name: Run tauri android init
      run: tauri android init
    - name: Run tauri android build
      run: tauri android build
  build-ios:
    runs-on: macOS-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Set up Rust
      uses: actions-rs/toolchain@0.1.8
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Install Xcode
      run: |
        # Update Xcode to the latest version
        sudo xcode-select --install
        # Accept Xcode license
        sudo xcodebuild -license accept
    - name: Set environment variables for iOS build
      run: |
        echo "APPLE_DEVELOPER_ACCOUNT=${{ secrets.APPLE_DEVELOPER_ACCOUNT }}" >> $GITHUB_ENV
        echo "APPLE_DEVELOPER_PASSWORD=${{ secrets.APPLE_DEVELOPER_PASSWORD }}" >> $GITHUB_ENV
        echo "APPLE_PROVISIONING_PROFILE=${{ secrets.APPLE_PROVISIONING_PROFILE }}" >> $GITHUB_ENV
    - name: Run tauri ios init
      run: tauri ios init
    - name: Run tauri ios build
      run: tauri ios build
