name: Tauri跨平台构建
on:
   workflow_dispatch:  # 允许手动触发
   push:
     branches: [ main ]  # 主分支推送时触发
 
jobs:
   build:
     runs-on: ubuntu-latest
     strategy:
       matrix:
         platform: [android, ios]  # 构建平台矩阵
     
     steps:
       - name: 检出代码
         uses: actions/checkout@v3
         
       - name: 设置Node.js
         uses: actions/setup-node@v3
         with:
           node-version: '16'
           
       - name: 安装依赖
         run: npm install
         
       - name: 安装Rust
         uses: actions-rs/toolchain@v1
         with:
           profile: minimal
           toolchain: stable
           target: wasm32-unknown-unknown
           
       - name: 安装Tauri CLI
         run: npm install @tauri-apps/cli
         
       - name: 安装平台特定依赖
         if: matrix.platform == 'android'
         run: |
           sudo apt-get update
           sudo apt-get install -y libwebkit2gtk-4.1-dev
           sudo apt-get install -y build-essential curl wget file
           sudo apt-get install -y libssl-dev libgtk-3-dev libayatana-appindicator3-dev
           
       - name: 构建应用
         run: npm run tauri build -- --target ${{ matrix.platform }}
         
       - name: 上传产物
         uses: actions/upload-artifact@v3
         with:
           name: ${{ matrix.platform }}-build
           path: src-tauri/target/release/bundle/${{ matrix.platform }}/*
