name: 'publish'
# 参考：https://github.com/tauri-apps/tauri-action

on:
  push:
    branches:
      - release
  # 添加 workflow_dispatch 以支持手动触发
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write  # 允许写入发布内容
    strategy:
      fail-fast: false  # 防止单个平台失败导致整个任务失败
      matrix:
        include:
          # macOS 平台配置
          - platform: 'macos-latest'   # Apple Silicon (M1/M2)
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest'   # Intel 芯片
            args: '--target x86_64-apple-darwin'
          
          # Linux 平台配置
          - platform: 'ubuntu-22.04'    # x86_64
            args: ''
          - platform: 'ubuntu-22.04'    # ARM64 支持
            args: '--target aarch64-unknown-linux-gnu'
          
          # Windows 平台配置
          - platform: 'windows-latest'  # x86_64
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4  # 检出代码

      # 设置 Node.js 环境
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*  # 使用最新的 LTS 版本

      # 安装 Rust 工具链
      - name: 安装 Rust 稳定版
        uses: dtolnay/rust-toolchain@stable
        with:
          # 仅 macOS 需要安装多目标编译支持
          targets: ${{ 
            matrix.platform == 'macos-latest' && 
            'aarch64-apple-darwin,x86_64-apple-darwin' || 
            (matrix.args == '--target aarch64-unknown-linux-gnu' && 
            'aarch64-unknown-linux-gnu' || '') 
          }}

      # Linux 系统依赖安装（包括 ARM64 支持）
      - name: 安装 Linux 依赖 (Ubuntu)
        if: startsWith(matrix.platform, 'ubuntu')  # 仅限 Ubuntu 平台
        run: |
          sudo apt-get update
          # 基础依赖
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev \
                                 libappindicator3-dev librsvg2-dev patchelf
          
          # 添加 ARM64 交叉编译支持
          if [ "${{ matrix.args }}" = "--target aarch64-unknown-linux-gnu" ]; then
            sudo dpkg --add-architecture arm64
            sudo apt-get update
            sudo apt-get install -y \
              gcc-aarch64-linux-gnu \
              libwebkit2gtk-4.0-dev:arm64 \
              libgtk-3-dev:arm64 \
              librsvg2-dev:arm64
          fi

      # 添加 ARM64 目标（仅限 Linux ARM64 构建）
      - name: 添加 Rust ARM64 目标
        if: matrix.args == '--target aarch64-unknown-linux-gnu'
        run: rustup target add aarch64-unknown-linux-gnu

      # 安装前端依赖
      - name: 安装前端依赖
        run: yarn install  # 根据实际需要替换为 npm/pnpm/bun

      # Tauri 构建和发布步骤
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 自动使用 GitHub Token
        with:
          tagName: app-v__VERSION__    # 自动替换为应用版本
          releaseName: '应用 v__VERSION__'
          releaseBody: '请下载附件安装此版本'
          releaseDraft: true           # 创建为草稿版
          prerelease: false            # 非预发布版
          args: ${{ matrix.args }}     # 传递平台参数
